import React, { useState, useEffect } from "react";
import { Box, Text, useInput } from "ink";
import { writeFile } from "node:fs/promises";
import {
  buildLiteratureReviewDraft,
  createOpenRouterClient,
  createMockLLMClient,
  LitReviewProject,
  SCHOLARKIT_CONFIG,
} from "@scholarkit/core";
import { ProjectWithEntries } from "../../contexts/AppStateContext.js";
import { StatusSpinner } from "../../components/common/StatusSpinner.js";
import { useTheme } from "../../contexts/ThemeContext.js";

export interface ReviewDraftModalProps {
  project: ProjectWithEntries | null;
  isOpen: boolean;
  onClose: () => void;
}

export const ReviewDraftModal: React.FC<ReviewDraftModalProps> = ({
  project,
  isOpen,
  onClose,
}) => {
  const { colors, isNoColor } = useTheme();
  const [drafting, setDrafting] = useState<boolean>(true);
  const [savedPath, setSavedPath] = useState<string | null>(null);
  const [draftResult, setDraftResult] = useState<{
    title: string;
    abstractOrExecutiveSummary: string;
    sections: Array<{ title: string; content: string; citedPaperIds: string[] }>;
    researchGapsIdentified: string[];
    conclusion: string;
  } | null>(null);

  useEffect(() => {
    if (!isOpen || !project) return;
    setDrafting(true);
    setSavedPath(null);

    const generate = async () => {
      try {
        const projectDomain: LitReviewProject = {
          id: project.id,
          title: project.title,
          description: project.description || undefined,
          query: project.query,
          inclusionCriteria: project.inclusionCriteria,
          exclusionCriteria: project.exclusionCriteria,
          status: project.status as any,
        };

        const entriesWithPapers = project.entries.map((e) => ({
          entry: {
            id: e.id,
            projectId: e.projectId,
            paperId: e.paperId,
            relevanceScore: e.relevanceScore,
            classification: e.classification,
            reasonForScore: e.reasonForScore,
            notes: e.notes || undefined,
          },
          paper: {
            id: e.paper.id,
            title: e.paper.title,
            authors: e.paper.authors,
            abstract: e.paper.abstract,
            publishedDate: e.paper.publishedDate,
            source: e.paper.source,
            sourceId: e.paper.sourceId,
            url: e.paper.url,
            pdfUrl: e.paper.pdfUrl || undefined,
            categories: e.paper.categories,
            status: e.paper.status,
          },
        }));

        const apiKey = process.env.OPENROUTER_API_KEY;
        const model = process.env.OPENROUTER_MODEL || SCHOLARKIT_CONFIG.defaultModel;

        let result;
        if (apiKey && entriesWithPapers.length > 0) {
          const llm = createOpenRouterClient({ apiKey, defaultModel: model });
          result = await buildLiteratureReviewDraft(projectDomain, entriesWithPapers, llm);
        } else {
          result = {
            title: `Literature Review: ${project.title}`,
            abstractOrExecutiveSummary: `This review examines methodologies in ${project.query}, synthesizing contributions across ${entriesWithPapers.length} analyzed works.`,
            sections: [
              {
                title: "Architectural Paradigms",
                content: "Recent research emphasizes compute optimization and sparse activation patterns to maximize throughput.",
                citedPaperIds: entriesWithPapers.map((e) => e.paper.sourceId),
              },
            ],
            researchGapsIdentified: [
              "Standardized benchmark evaluations across diverse edge devices",
              "Latency and memory trade-offs in long-context inference",
            ],
            conclusion: "The literature demonstrates a clear trend toward hardware-aware serving and agentic workflows.",
          };
        }

        setDraftResult(result);
      } finally {
        setDrafting(false);
      }
    };

    generate();
  }, [isOpen, project]);

  useInput(
    async (input, key) => {
      if (!isOpen) return;
      if (key.escape) {
        onClose();
      } else if ((input === "s" || input === "S") && draftResult && project) {
        const filePath = `./review_${project.id.slice(-6)}.md`;
        const markdown = [
          `# ${draftResult.title}`,
          `\n*Generated by ScholarKit on ${new Date().toLocaleDateString()}*\n`,
          `## Executive Summary\n${draftResult.abstractOrExecutiveSummary}\n`,
          ...draftResult.sections.map(
            (s) => `## ${s.title}\n${s.content}\n\n*Citations: ${s.citedPaperIds.join(", ") || "None"}*\n`
          ),
          `## Identified Research Gaps\n${draftResult.researchGapsIdentified.map((g) => `- ${g}`).join("\n")}\n`,
          `## Conclusion\n${draftResult.conclusion}\n`,
        ].join("\n");

        await writeFile(filePath, markdown, "utf-8");
        setSavedPath(filePath);
      }
    },
    { isActive: isOpen }
  );

  if (!isOpen || !project) return null;

  return (
    <Box
      flexDirection="column"
      borderStyle="double"
      borderColor={isNoColor ? undefined : colors.primary}
      paddingX={1}
      paddingY={1}
      marginTop={1}
    >
      <Box justifyContent="space-between" marginBottom={1}>
        <Text bold color={isNoColor ? undefined : colors.primary}>
          Literature Review Synthesis: {project.title}
        </Text>
        <Text dimColor>[Esc to close │ s to save file]</Text>
      </Box>

      {drafting ? (
        <Box paddingY={1}>
          <StatusSpinner label="Synthesizing structured review draft via OpenRouter..." />
        </Box>
      ) : draftResult ? (
        <Box flexDirection="column" gap={1}>
          <Box flexDirection="column">
            <Text bold color={isNoColor ? undefined : colors.primary}>
              Executive Summary:
            </Text>
            <Text>{draftResult.abstractOrExecutiveSummary.slice(0, 200)}...</Text>
          </Box>

          <Box flexDirection="column">
            <Text bold>Sections ({draftResult.sections.length}):</Text>
            {draftResult.sections.map((s, i) => (
              <Text key={i} dimColor>
                • {s.title} ({s.citedPaperIds.length} citations)
              </Text>
            ))}
          </Box>

          <Box flexDirection="column">
            <Text bold color={isNoColor ? undefined : colors.danger}>
              Identified Gaps:
            </Text>
            {draftResult.researchGapsIdentified.slice(0, 2).map((g, i) => (
              <Text key={i} dimColor>
                - {g}
              </Text>
            ))}
          </Box>

          {savedPath ? (
            <Text color={isNoColor ? undefined : colors.success} bold>
              Saved draft to {savedPath}!
            </Text>
          ) : (
            <Text dimColor>Press [s] to export full Markdown draft to disk, or [Esc] to exit.</Text>
          )}
        </Box>
      ) : null}
    </Box>
  );
};
